In [58]:
from glob import glob
from PIL import Image
import numpy as np
from os.path import basename
import fnmatch
import cv2
import pandas as pd
from sklearn.model_selection import train_test_split

#Path of the files:
path = "/Users/MariaNuila/Desktop/CECS406/IDC_regular_ps50_idx5/*/*/*.png"
width, height = 50, 50
pictures = glob(path)

#Separate images based on classification
nonIDC =  fnmatch.filter(pictures, '*class0.png')
IDC = fnmatch.filter(pictures, '*class1.png')



In [63]:
#Create training and testing data set from pictures
x = []
y = [] #labels
for pic in pictures[0:5]:
    image = cv2.imread(pic)
    x.append(cv2.resize(image, (width, height),interpolation=cv2.INTER_CUBIC))
    if pic in nonIDC:
        y.append(0)
    if pic in IDC:
        y.append(1)

df = pd.DataFrame()
df["images"] = x
df["labels"] = y
x=np.array(x)
x=x/255.0

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2)


[[[0.77647059 0.65490196 0.81960784]
  [0.77254902 0.6627451  0.85490196]
  [0.82745098 0.74901961 0.88235294]
  ...
  [0.76078431 0.67058824 0.8627451 ]
  [0.74117647 0.61568627 0.85098039]
  [0.74509804 0.61568627 0.85490196]]

 [[0.72941176 0.6        0.81176471]
  [0.79215686 0.70980392 0.85098039]
  [0.90196078 0.86666667 0.93333333]
  ...
  [0.73333333 0.60784314 0.84705882]
  [0.6627451  0.54117647 0.79607843]
  [0.65882353 0.50980392 0.79215686]]

 [[0.6627451  0.52941176 0.78823529]
  [0.78823529 0.68235294 0.86666667]
  [0.90588235 0.85098039 0.92156863]
  ...
  [0.61568627 0.46666667 0.79215686]
  [0.76470588 0.6745098  0.86666667]
  [0.65098039 0.52941176 0.79215686]]

 ...

 [[0.96470588 0.95686275 0.95686275]
  [0.96078431 0.95686275 0.95686275]
  [0.96470588 0.96078431 0.96078431]
  ...
  [0.9372549  0.92941176 0.9372549 ]
  [0.78431373 0.67843137 0.82352941]
  [0.8        0.73333333 0.88235294]]

 [[0.96470588 0.95686275 0.96078431]
  [0.96078431 0.95686275 0.95686275]
